// 部门列表
let dataDeptList = [
  {
    id: '0',
    deptName: '华东分部',
    orderNo: 1,
    createTime: '2017-04-03 03:41:40',
    remark: '情二今引车你布斯委保选以况备真义青长',
    status: '0',
    children: [
      {
        id: '0-0',
        deptName: '研发部',
        orderNo: 1,
        createTime: '2011-06-07 06:07:13',
        remark: '细回书处处技强色号子走命',
        status: '1',
        parentDept: '0',
      },
      {
        id: '0-1',
        deptName: '市场部',
        orderNo: 2,
        createTime: '2019-11-29 09:47:07',
        remark: '分非始却查正果转写除太写任身件八步共时',
        status: '0',
        parentDept: '0',
      },
      {
        id: '0-2',
        deptName: '商务部',
        orderNo: 3,
        createTime: '1979-02-18 14:13:05',
        remark: '事声条西对以律活意太石山其毛写产并',
        status: '0',
        parentDept: '0',
      },
      {
        id: '0-3',
        deptName: '财务部',
        orderNo: 4,
        createTime: '2019-09-05 07:59:51',
        remark: '管意反便活族新例增任务',
        status: '1',
        parentDept: '0',
      },
    ],
  },
  {
    id: '1',
    deptName: '华南分部',
    orderNo: 2,
    createTime: '2018-11-10 16:42:58',
    remark: '业月经新观论适最己重路整总其各格只如她',
    status: '0',
    children: [
      {
        id: '1-0',
        deptName: '研发部',
        orderNo: 1,
        createTime: '1997-04-27 00:53:56',
        remark: '取圆力和产元王传展看很好起作些元',
        status: '1',
        parentDept: '1',
      },
      {
        id: '1-1',
        deptName: '市场部',
        orderNo: 2,
        createTime: '1970-07-17 04:55:59',
        remark: '长看重南边式育须说增万如',
        status: '0',
        parentDept: '1',
      },
      {
        id: '1-2',
        deptName: '商务部',
        orderNo: 3,
        createTime: '2010-10-01 07:14:16',
        remark: '作代级形格消角开么率究素来',
        status: '0',
        parentDept: '1',
      },
      {
        id: '1-3',
        deptName: '财务部',
        orderNo: 4,
        createTime: '2019-11-24 06:55:32',
        remark: '成交矿他即做任算商形组生',
        status: '0',
        parentDept: '1',
      },
    ],
  },
  {
    id: '2',
    deptName: '西北分部',
    orderNo: 3,
    createTime: '1981-03-10 22:46:15',
    remark: '类那确里情通见自天志活正消只记',
    status: '1',
    children: [
      {
        id: '2-0',
        deptName: '研发部',
        orderNo: 1,
        createTime: '1987-02-13 02:15:16',
        remark: '委受你由划传些生应间阶导',
        status: '1',
        parentDept: '2',
      },
      {
        id: '2-1',
        deptName: '市场部',
        orderNo: 2,
        createTime: '1985-09-20 21:00:50',
        remark: '期龙可整立意织白式议技局复方率共历认府组',
        status: '0',
        parentDept: '2',
      },
      {
        id: '2-2',
        deptName: '商务部',
        orderNo: 3,
        createTime: '1995-06-12 19:52:38',
        remark: '界数层国来其信完快表太又根花为素商但',
        status: '1',
        parentDept: '2',
      },
      {
        id: '2-3',
        deptName: '财务部',
        orderNo: 4,
        createTime: '1978-01-11 22:25:54',
        remark: '压要发正上可前算他位存称状',
        status: '0',
        parentDept: '2',
      },
    ],
  },
];
